services:
  mailhog:
    container_name: mailhog
    image: 'jcalonso/mailhog:latest'
    ports:
      - '1025:1025'
      - '48001:8025'
    restart: unless-stopped
    networks:
      - app-network

  redis:
    container_name: redis
    image: 'redis:7.4-alpine3.20'
    ports:
      - "${DOCKER_REDIS_PORT}:6379"
    networks:
      - app-network
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]

  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "12345678"
    networks:
      - app-network

  mysql:
    container_name: mysql
    image: 'mysql:8.0'
    working_dir: /application
    volumes:
      - my-dataVolume:/var/lib/mysql
      - '.:/application'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=crm
      - MYSQL_USER=crm-user
      - MYSQL_PASSWORD=password
    ports:
      - '48002:3306'
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: 'nginx:alpine'
    working_dir: /application
    volumes:
      - '.:/application'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'
    networks:
      - app-network

  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    working_dir: /application
    networks:
      - app-network
    external_links:
      - mailhog
    depends_on:
      - mysql
      - redis
      - mailhog
      - nginx
    volumes:
      - '.:/application'
      - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
      - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'
    command: php-fpm

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    container_name: worker
    working_dir: /application
    volumes:
      - ./:/application
    networks:
      - app-network
    depends_on:
      - mysql
      - redis
    command: supervisord -c /etc/supervisor/conf.d/supervisord.conf

volumes:
  my-dataVolume:

networks:
  app-network:
    driver: bridge
